# Generated by Django 3.2.13 on 2022-10-07 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eithers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('eithers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eithers.eithers')),
            ],
        ),
    ]
