# Generated by Django 3.2.13 on 2022-10-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eithers', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='eithers',
            name='issue_a_vote',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eithers',
            name='issue_b_vote',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
